### ISSUE TITLE
Try to remove limitations.

### ISSUE THREAD

**Issue by MariasStory** [BromiumLabs/PackerAttacker#7]
Hi Guys,

Good job.

First of all I would like to know how do you compare to https://github.com/malwaremusings/unpacker.

The most important question is about the "detours". Why did you peak this framework and can't you do the job with another "free" tools?

In general I am very interested in such automated solutions.

Greetings,
Tolik

**Comment by vadimkotov** [comment]
1. What limitations are you talking about?
2. Unpacker seems to focus on API calls and behaviors commonly seen in packers, we on the other hand are trying to implement a generic approach, where we dump all the memory that has been written and executed. There's some work to do but it gives promising results.
3. We chose detours because it's easy to use and so we were able to quickly throw together a working prototype. Also it's free for non-commercial use. Do you know a better hooking library with the same capabilities that is free?

**Comment by vadimkotov** [comment]
Ok I familiarized myself better with the Unpacker's code, they do seem to use the writeable / executable memory approach. I don't have much time to dive in too deep and give you the fine-grained differences. However it would be interesting to try some of their tricks. So thanks for sharing this information.

If you're interested in automated unpacking feel free to contribute to the project. There are millions of things to do and just 2 people working on the project in their spare time ;)

**Comment by MariasStory** [comment]
Thanks Vadim,

Indeed, it is an interesting topic and I like the way you approach this.

I am working for a big company and need to give answers to some complex cases (like Dridex :-)) in a timely meter, and I don't like spending time manually unpacking staff.

I am definitely looking for reasonable solution in this direction.

Would like to support you, but I am not sure if and when I will have time :-)

Greetings,
Tolik
